[project]
name = "isaac_lab_quadruped"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "isaaclab[all,isaacsim]==2.3.0",
    "skrl[torch]",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
override-dependencies = [
    "torch==2.4.0", 
    "torchvision==0.19.0",
    "pywin32==306; sys_platform == 'win32'", 
]

[tool.uv.extra-build-dependencies]
flatdict = ["setuptools<82.0.0", "wheel"]

[tool.hatch.build.targets.wheel]
packages = ["source/isaac_lab_quadruped/isaac_lab_quadruped"]

[tool.uv.sources]
isaacsim = { index = "nvidia" }
torch = { index = "torch" }
torchvision = { index = "torch" }

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com/"
explicit = true

[[tool.uv.index]]
name = "torch"
url = "https://download.pytorch.org/whl/cu121" 
explicit = true
